version: '4.3'

services:
  app:
    build:
      context: ./api-project/vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: 1000
    image: sail-8.3/app
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    volumes:
        - './api-project:/var/www/html'
    networks:
        - app-network
    env_file:
      - ./api-project/.env
    depends_on:
        - db   

  frontend:
    build:
      context: ./front-project
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run serve"
    image: vue-frontend
    container_name: vue-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./front-project:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app
      - frontend
  
  db:
    image: 'mysql/mysql-server:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'modelsDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - './volumes/database:/var/lib/mysql'
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
